<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="branch2" Id="{0bb389dd-2447-041b-0c77-c9844855d835}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM branch2
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="branch2">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>