<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="git_Test" Id="{ff817349-10a0-05f9-0332-d8be63f4b9f3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM git_Test
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="git_Test">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>