<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="mainBranch" Id="{0d212e3f-3bd6-0024-34c7-95813e41232f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM mainBranch
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="mainBranch">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>