<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="originRepo" Id="{b4668f6f-2cb5-0ea5-249d-7446f2c7583a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM originRepo
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="originRepo">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>