<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="originRepo2" Id="{aaa911db-0e3a-01b3-148d-07ef2642fbc3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM originRepo2
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="originRepo2">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>